### ISSUE TITLE
Games don´t launch with the script in Steam Flatpak

### ISSUE THREAD

**Issue by ScorchingLenard** [tactikauan/thcrap-steam-proton-wrapper#4]
So I see that this was a problem before and was supposed to be fixed but I've been having this issue where the Touhou games don´t launch with the script, I can patch the games and run them in english just fine but I can´t get them to play through the Steam launcher, I'm using the Flatpak version and I'm sure the issue lies there because I even tested doing the exact same things in a normal package version of Steam and worked without a problem first try.
It may be that the Steam Flatpak doesn´t have the right permissions, I've been trying to give steam access to the folders where the script and the thcrap is among other things through Flatseal but it hasn´t work, I'm fairly new to this and don´t really get what most of the permissions options do. Is the problem there or what else could it be?

**Comment by nerusuki** [comment]
Flatpak applications run inside sandboxes and can´t normally access files from outside their environment. In this case, Steam can't actually find the script to run, and that's why the games don't launch. Tools like gamescope overcome this by providing extension packages for running inside Steam Flatpak. I plan on doing the same, however I still have to investigate how to publish Flatpak packages.

For now, a quick solution is to put the script inside ```/home/$USER/.var/app/com.valvesoftware.Steam``` which gets mapped to the home directory inside the sandbox, and can be called by providing the full path ```/home/$USER/thcrap_proton``` in the launch options.

**Comment by ScorchingLenard** [comment]
I did as you said, moving the script to the folder inside the sandbox and it did work without a problem, at least in the games I tried it with, which where 17 and 18.
Thanks for the solution and looking forward to the work you are doing for it to have full compatibility with the Flatpak.

**Comment by nerusuki** [comment]
It's up on Flathub. See if it works for you:

`flatpak install flathub com.valvesoftware.Steam.Utility.thcrap_steam_proton_wrapper`
